#%RAML 1.0 Trait

responses:
  200:
    headers:
      Cache-Control:
        description: Some Description for CacheControl
      Expires:
        type: datetime
        description: Some Desc for expires